"""minor fix

Revision ID: 793c40f15cf3
Revises: 20de74e722ec
Create Date: 2025-06-03 21:23:48.113858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '793c40f15cf3'
down_revision = '20de74e722ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.Integer(), nullable=False))
        batch_op.alter_column('date_created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['date_created'])
        batch_op.create_foreign_key(None, 'tasks', ['task_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('date_created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('task_id')

    # ### end Alembic commands ###
