"""minor fix

Revision ID: daa0939ace74
Revises: 2bf547590ea3
Create Date: 2025-06-03 23:09:33.022995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daa0939ace74'
down_revision = '2bf547590ea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('assigned_to',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('assigned_to',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
