"""adds favourite column to the projects table

Revision ID: ee201c5b7d3f
Revises: daa0939ace74
Create Date: 2025-06-03 23:31:15.680031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee201c5b7d3f'
down_revision = 'daa0939ace74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('favorite')

    # ### end Alembic commands ###
